const LOBBY_PHASE = 'LOBBY';
const QUESTION_PHASE = 'QUESTION';
const TURN_GUESS_PHASE = 'TURN_GUESS';
const TURN_REVEAL_PHASE = 'TURN_REVEAL';
const SCOREBOARD_PHASE = ' SCOREBOARD';
const ROOM_CODE_LENGTH = 4;
const ROOM_CODE_SYMBOLS = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';

export {
  LOBBY_PHASE,
  QUESTION_PHASE,
  TURN_GUESS_PHASE,
  TURN_REVEAL_PHASE,
  SCOREBOARD_PHASE,
  ROOM_CODE_LENGTH,
  ROOM_CODE_SYMBOLS
};
