const LOBBY_PHASE = 'LOBBY';
const QUESTION_PHASE = 'QUESTION';
const TURN_GUESS_PHASE = 'TURN_GUESS';
const TURN_REVEAL_PHASE = 'TURN_REVEAL';
const SCOREBOARD_PHASE = ' SCOREBOARD';

export {
  LOBBY_PHASE,
  QUESTION_PHASE,
  TURN_GUESS_PHASE,
  TURN_REVEAL_PHASE,
  SCOREBOARD_PHASE
};
